/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'stepper_144pin.debug_GCC+NUCLEO-C5A3ZG' 
 * Target:  'debug_GCC+NUCLEO-C5A3ZG' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:RCC@2.1.0 */
#define USE_EXTERNAL_ENV


#endif /* PRE_INCLUDE_GLOBAL_H */
