/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'autoloader_fw.debug_GCC+STM32C591ZGT6' 
 * Target:  'debug_GCC+STM32C591ZGT6' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::File System:STM32CubeMX2 Config:FileX@2.1.0 */
#define FX_INCLUDE_USER_DEFINE_FILE
/* STMicroelectronics::USB:STM32CubeMX2 Config:USBX@2.1.0 */
#define UX_INCLUDE_USER_DEFINE_FILE


#endif /* PRE_INCLUDE_GLOBAL_H */
