/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'autoloader_fw.debug_GCC+NUCLEO-C5A3ZG' 
 * Target:  'debug_GCC+NUCLEO-C5A3ZG' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:RCC@2.1.0 */
#define USE_EXTERNAL_ENV
/* STMicroelectronics::File System:STM32CubeMX2 Config:FileX@2.1.0 */
#define FX_INCLUDE_USER_DEFINE_FILE
/* STMicroelectronics::USB:STM32CubeMX2 Config:USBX@2.1.0 */
#define UX_INCLUDE_USER_DEFINE_FILE


#endif /* PRE_INCLUDE_GLOBAL_H */
