/**
 * @file modbus_port.c
 * @brief Modbus RTU portable layer for STM32C5A3ZG (CubeMX 2.0 HAL).
 *        Uses USART1 (label: mb_slave) for RS-485 half-duplex and TIM15 (label: MB_TIMER) as the inter-frame timeout timer.
 *
 * @copyright Copyright (c) 2022 Embedded Design Solutions, LLC.  All Rights Reserved.
 */

/*******************************************************************************
 * Includes
 *******************************************************************************/
#include "modbus_port.h"
#include "app_console.h"
#include "mx_hal_def.h"

#include <stdbool.h>
#include <stdint.h>

#include "FreeRTOS.h"
#include "modbus_slave.h"
#include "task.h"

/*******************************************************************************
 * Module Macros
 *******************************************************************************/

/* RS-485 DE (driver enable) pin — replace with your CubeMX IOC pin labels */
#if 0
#define RS485_DE_PIN GPIO_PIN_0
#define RS485_DE_PORT GPIOA
#endif

/*
 * TIM15 tick frequency in Hz after the CubeMX prescaler.
 * Set TIM15 Prescaler in CubeMX to: (APB2_TIMER_CLK_HZ / MODBUS_TIMER_CLK_HZ) - 1
 * Example: 64 MHz APB2 timer clock with Prescaler = 63 → MODBUS_TIMER_CLK_HZ = 1 000 000
 */
#define MODBUS_TIMER_CLK_HZ 1000000UL

/*******************************************************************************
 * Module Typedefs
 *******************************************************************************/

/*******************************************************************************
 * Module Variable Definitions
 *******************************************************************************/
static TickType_t last_frame_time = 0;
static modbus_slave_t* s_mb_ctx = NULL;
static volatile bool s_is_writing = false;
static uint8_t s_rx_byte = 0U;

/*******************************************************************************
 * External Handle Declarations (generated by CubeMX in main.c / usart.c / tim.c)
 *******************************************************************************/

/*******************************************************************************
 * Function Prototypes
 *******************************************************************************/
static void set_for_rx(void);
static void set_for_tx(void);
static void mb_uart_tx_cplt_cb(hal_uart_handle_t* huart);
static void mb_uart_rx_cplt_cb(hal_uart_handle_t* huart, uint32_t size_byte, hal_uart_rx_event_types_t rx_event);
static void mb_timer_update_cb(hal_tim_handle_t* htim);

void ui_slave_init(void* context);
void ui_slave_xmit_frame(uint8_t* data, uint16_t data_len);
void ui_slave_set_timer_period_us(int period_us);
void ui_slave_stop_timer(void);
void ui_slave_reset_timer(void);
void ui_slave_start_read(uint8_t* byte);
bool ui_slave_is_writing(void);

static void Error_Handler(void);

modbus_slave_port_fns_t ui_slave_port_fns = {
    .init = ui_slave_init,
    .xmit_frame = ui_slave_xmit_frame,
    .set_timer_period_us = ui_slave_set_timer_period_us,
    .stop_timer = ui_slave_stop_timer,
    .reset_timer = ui_slave_reset_timer,
    .start_read = ui_slave_start_read,
    .is_writing = ui_slave_is_writing,
};

/*******************************************************************************
 * Public Function Definitions
 *******************************************************************************/

modbus_slave_port_fns_t* get_ui_port_fns(void) {
  return &ui_slave_port_fns;
}

TickType_t modbus_portable_get_last_frame_time(void) {
  return last_frame_time;
}

void ui_slave_init(void* context) {
  s_mb_ctx = (modbus_slave_t*)context;
  if (HAL_UART_RegisterTxCpltCallback(mb_slave_gethandle(), mb_uart_tx_cplt_cb) != HAL_OK) {
    Error_Handler();
  }
  if (HAL_UART_RegisterRxCpltCallback(mb_slave_gethandle(), mb_uart_rx_cplt_cb) != HAL_OK) {
    Error_Handler();
  }
  if (HAL_TIM_RegisterUpdateCallback(mb_timer_gethandle(), mb_timer_update_cb) != HAL_OK) {
    Error_Handler();
  }
  if (HAL_TIM_Start_IT(mb_timer_gethandle()) != HAL_OK) {
    Error_Handler();
  }
  // Start the first receive operation so we can receive the first byte of a Modbus frame.
  ui_slave_start_read(NULL);
}

void ui_slave_xmit_frame(uint8_t* data, uint16_t data_len) {
  if (data == NULL) {
    return;
  }
  if (HAL_UART_AbortReceive_IT(mb_slave_gethandle()) != HAL_OK) {
    Error_Handler();
  }
  set_for_tx();
  s_is_writing = true;
  if (HAL_UART_Transmit_IT(mb_slave_gethandle(), data, (uint32_t)data_len) != HAL_OK) {
    s_is_writing = false;
    set_for_rx();
    Error_Handler();
  }
}

void ui_slave_set_timer_period_us(int period_us) {
  uint32_t ticks = (MODBUS_TIMER_CLK_HZ / 1000000UL) * (uint32_t)period_us;
  if (HAL_TIM_SetPeriod(mb_timer_gethandle(), ticks - 1U) != HAL_OK) {
    Error_Handler();
  }
}

void ui_slave_stop_timer(void) {
  if (HAL_TIM_Stop_IT(mb_timer_gethandle()) != HAL_OK) {
    Error_Handler();
  }
}

void ui_slave_reset_timer(void) {
  if (HAL_TIM_SetCounter(mb_timer_gethandle(), 0U) != HAL_OK) {
    Error_Handler();
  }
}

void ui_slave_start_read(uint8_t* byte) {
  (void)byte;
  set_for_rx();
  hal_status_t status = HAL_UART_Receive_IT(mb_slave_gethandle(), &s_rx_byte, 1U);
  if ((status != HAL_OK) && (status != HAL_BUSY)) {
    Error_Handler();
  }
}

bool ui_slave_is_writing(void) {
  return s_is_writing;
}

/*******************************************************************************
 * Private Function Definitions
 *******************************************************************************/

/**
 * @brief Drives the RS-485 DE pin low to enable the receive path.
 */
static void set_for_rx(void) {
  // HAL_GPIO_WritePin(RS485_DE_PORT, RS485_DE_PIN, GPIO_PIN_RESET);
}

/**
 * @brief Drives the RS-485 DE pin high to enable the transmit path.
 */
static void set_for_tx(void) {
  // HAL_GPIO_WritePin(RS485_DE_PORT, RS485_DE_PIN, GPIO_PIN_SET);
}

/*******************************************************************************
 * HAL Registered Callbacks (per-handle, registered in ui_slave_init)
 *******************************************************************************/

/**
 * @brief UART TX-complete callback registered on mb_slave handle.
 *        Polls TC until the shift register drains, then switches RS-485 to RX
 *        and re-arms single-byte reception.
 * @param huart Handle of the UART peripheral that completed transmission.
 */
static void mb_uart_tx_cplt_cb(hal_uart_handle_t* huart) {
  /* Poll TC so the last bit has left the wire before driving DE low */
  while (LL_USART_IsActiveFlag_TC((USART_TypeDef*)((uint32_t)(huart->instance))) == 0U) {
  }
  s_is_writing = false;
  set_for_rx();
  hal_status_t status = HAL_UART_Receive_IT(mb_slave_gethandle(), &s_rx_byte, 1U);
  if ((status != HAL_OK) && (status != HAL_BUSY)) {
    Error_Handler();
  }
}

/**
 * @brief UART RX-complete callback registered on mb_slave handle.
 *        Forwards the received byte to the Modbus stack and re-arms reception.
 * @param huart   Handle of the UART peripheral that received a byte.
 * @param size_byte Number of bytes received (unused — always 1).
 * @param rx_event  Reception event type (unused).
 */
static void mb_uart_rx_cplt_cb(hal_uart_handle_t* huart, uint32_t size_byte, hal_uart_rx_event_types_t rx_event) {
  (void)huart;
  (void)size_byte;
  (void)rx_event;
  if (s_mb_ctx != NULL) {
    MB_RxByte(s_mb_ctx, s_rx_byte);
  }
  hal_status_t status = HAL_UART_Receive_IT(mb_slave_gethandle(), &s_rx_byte, 1U);
  if ((status != HAL_OK) && (status != HAL_BUSY)) {
    Error_Handler();
  }
}

/**
 * @brief TIM15 update callback registered on the mb_timer handle.
 *        Notifies the Modbus stack of a frame timeout when TIM15 expires.
 * @param htim Handle of the timer peripheral that expired.
 */
static void mb_timer_update_cb(hal_tim_handle_t* htim) {
  (void)htim;
  if (s_mb_ctx != NULL) {
    MB_TimerExpired(s_mb_ctx);
  }
}

static void Error_Handler(void) {
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  app_console_print("[ERROR] HAL error occurred. Halting.\r\n");
  while (1) {
    /* Infinite loop */
  }
}
